openapi: 3.0.0
info:
  description: ""
  version: "0.1.0"
  title: "Swagger Petstore"
servers:
  - url: /v1
tags:
- name: "Similarity"
  description: "Post reviews and get the simirality between a reviewer and a user"
paths:
  /profile/similarity:
    post:
      tags:
      - "Similarity"
      summary: "Get similarity from posted reviews"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Data"
      responses:
        201:
          description: "Similarity between a user and a reviewer"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReviewsResponse"
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:        
      type: apiKey
      in: header       
      name: X-API-KEY
  schemas:
    Data:
      type: "object"
      required:
      - "reviews"
      properties:
        user_id:
          type: "string"
        user_text:
          type: "string"
        reviewer_id:
          type: "string"
        reviewer_text:
          type: "string"
    ReviewsResponse:
      type: "object"
      properties:
        similarity:
          type: number
          format: float